services:
  ai-baby-monitor:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: AI-Baby-Monitor
    restart: unless-stopped
    ports:
      - "8847:8847"
    
    # Environment variables
    environment:
      - RTSP_URL=${RTSP_URL}
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    
    # Volume mappings
    volumes:
      # Map recordings directory (MONITOR_RECORDINGS_DIR)
      - ${HOME}/baby-monitor:/app/baby-monitor
    # Health check override
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8847/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  recordings:
    driver: local
  cache:
    driver: local
  logs:
    driver: local

networks:
  default:
    name: baby-monitor-network
    driver: bridge
